project:
  type: website

website:
  title: "Biomarker One Day"
  description: "This is our blog in oncology"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/zq2323/us

format:
  html:
    theme: cosmo
    css: styles.css
