---
title: 'Mutiple level calculation 4'
date: '2023-04-11'
author: Qing Zou
categories: ['R', 'rtables']
description: 'multiple level counts more than 2 levels'
execute:
  message: false
  warning: false
editor_options:
  chunk_output_type: console
---


```{r rcell3sd45}
#| echo: false
#| eval: true

#' a pair of functions sprintf_format and format_values used for rcell
#'
#' @param n Unique number of events for the current category
#' @param N Total number of events under the split column
#' @param decimal Number of decimal to display
#' @param type to decide if the denominator n/N(%) in the result
#' @keywords sprintf_format
#'
#' @return
sprintf_format_helper <- function(n, N, decimal = 1, type = "n(%)") {
  showN <- NULL
  if (type == "n/N(%)"){
    showN <- "/%.0f"
  }

  if (n == 0) {
    fmt <- sprintf_format(paste0("%.0f", showN))
  } else if (n == N) {
    # if pct == 100%, then show (100) instead of (100.0)
    fmt <- sprintf_format(paste0("%.0f", showN, " ", "(%.0f)"))
  } else {
    fmt <- sprintf_format(paste0("%.0f", showN, " (%.", decimal, "f)"))
  }

  return(fmt)
}


#' a pair of functions sprintf_format and format_values used for rcell
#'
#' @param n Unique number of events for the current category
#' @param N Total number of events under the split column
#' @param type to decide if the denominator n/N(%) in the result
#'
#' @keywords format_values
#' @example
#' rcell(x = format_values_helper(1, 10),
#'       format = sprintf_format_helper(1, 10))
#'
#' rcell(x = format_values_helper(1, 10, type = "n/N(%)"),
#'       format = sprintf_format_helper(1, 10, type = "n/N(%)"))
#'
#' rcell(x = format_values_helper(10, 10),
#'       format = sprintf_format_helper(10, 10))
#'
#' @return
format_values_helper <- function(n, N, type = "n(%)") {
  showN <- NULL
  if (type == "n/N(%)"){
    showN <- N
  }
  if (n == 0) {
    value <- c(0, showN)
  } else {
    value <- c(n, showN, n / N * 100)
  }

  return(value)
}

#' Display rtables in html
#'
#' @param table a rtables object
#' @param to_html export to HTML. Default TRUE
#'
#' @return a html table
#' @export
table_to_html <- function(table, to_html = TRUE) {
  stopifnot(!is.null(table), class(table) %in% c("TableTree", "ElementaryTable"))

  extra_css <- "
  .tabwid {overflow-x: scroll; display: block;}
  .tabwid table td p {min-width: 170px !important;}
  .tabwid table td:first-child > p {min-width: 200px !important;}
  .tabwid table tr:hover {background-color: #ffff99 !important;}
  "
  flextable::set_flextable_defaults(
    font.family = ifelse(to_html, "Source Sans Pro", "Verdana"),
    extra_css = extra_css
  )

  ft <- rtables::tt_to_flextable(table) %>%
    flextable::border_remove() %>%
    flextable::bold(bold = TRUE, part = "header") %>%
    flextable::hline_top(part = "body") %>%
    flextable::hline_bottom(part = "body") %>%
    flextable::autofit()

  if (to_html) {
    flextable::htmltools_value(ft)
  } else {
    ft
  }
}

count_items_cfun <- function(df,
                        labelstr,
                        .spl_context,
                        n_var,
                        n_unique_keys = NULL,
                        N_var = NULL,
                        N_index = NULL,
                        N_unique_keys = NULL,
                        empty_row = FALSE,
                        hide_value = FALSE,
                        format = "n/N(%)") {

  # caculate the value
  df_n <- df
  if (!is.null(n_unique_keys)) {
    df_n <- df %>% distinct(across(n_unique_keys), .keep_all = T)
  }
  x <- df_n[[n_var]]
  n <- sum(x[!is.na(x)])

  cur_index <- which(.spl_context[["value"]] == labelstr)
  # View(df)
  if (!is.null(N_var)) {

    # get N of parent for denomitor caculation
    if (!is.null(N_index)) {
      parent_df <- .spl_context$full_parent_df[[N_index]][.spl_context[["cur_col_subset"]][[N_index]], ]
    } else {
      parent_df <- .spl_context$full_parent_df[[cur_index - 1]][.spl_context[["cur_col_subset"]][[cur_index - 1]], ]
    }

    if (!is.null(N_unique_keys)) {
      parent_df <-  parent_df %>% distinct(across(N_unique_keys), .keep_all = T)
    }


    parent_x <- parent_df[[N_var]]
    parent_N <- sum(!is.na(parent_x[!is.na(parent_x)]))

    # get current value to check if it match the last value of levels, for empty row
    # !Start
    var_levels <- length(.spl_context$split)
    curr_var_level_val <- .spl_context$value[[nrow(.spl_context)]]
    last_var_level_val <-
      .spl_context$full_parent_df[[nrow(.spl_context)]][[.spl_context$split[var_levels]]] %>%
      levels() %>%
      tail(1)
    if (curr_var_level_val == last_var_level_val & empty_row) {
      ret <- in_rows(
        .names = c(labelstr, " "),
        .list = list(c(format_values_helper(n, parent_N, type = format)), NULL),
        .formats = c(sprintf_format_helper(n, parent_N, type = format), "xx")
      )
    } else {
      rc <- rcell(
        x = format_values_helper(n, parent_N, type = format),
        format = sprintf_format_helper(n, parent_N, type = format)
      )
      ret <- in_rows(.names = labelstr, rc)
    }
    # !End
  } else {
    rc <- rcell(
      x = ifelse(hide_value, "", n),
      format = "xx"
    )
    ret <- in_rows(.names = labelstr, rc)
  }
  return(ret)
}
```


```{r cal1}
library(rtables)
library(formatters)
library(dplyr)
library(stringr)
```

## Summary counts more than 2rd level

```{r cal2}
#| echo: false
#| eval: true
df <- data.frame(SUBJID = paste0("S", 1:10),
                 GROUP = factor(sample(c("A", "B", "C"), 10, replace = T), levels = c("A", "B", "C")),
                 AVAL = sample.int(20, 10)
                 )

df <- df %>% mutate(level_1 = ifelse(3 < AVAL & AVAL <=18, "level 1", NA_character_),
                    level_2 = ifelse(5 < AVAL & AVAL <=15, "level 2", NA_character_),
                    level_3 = ifelse(8 < AVAL & AVAL  <=12, "level_3", NA_character_)
                    )
df <- df %>% mutate(across(paste0('level_', 1:3),
                           ~factor(.)))
df <- df %>% mutate(across(paste0('level_', 1:3),
                           ~ifelse(!is.na(.x), 1, .x),
                           .names = "{gsub('level','aval', .col)}"))
```
```{r cal2sd }
#| echo: false
#| eval: true
#| message: FALSE
knitr::kable(df, "html")%>%
  kableExtra::kable_styling(font_size = 16)
```


```{r cal2dfg}
#| echo: true
#| eval: true

col_counts <- table(df$GROUP)
col_counts <- c(col_counts, sum(col_counts))

tbl_recipe <- basic_table() %>%
  rtables::split_cols_by(var = "GROUP") %>%
  add_overall_col("All") %>%
  ## 1st-level row-wise splitting, and its column-wise analysis function
  rtables::split_rows_by("level_1", split_fun = remove_split_levels(c(NA_character_))) %>%
  rtables::summarize_row_groups(cfun = count_items_cfun,
                                extra_args = list(n_var = "aval_1", n_unique_keys = "SUBJID", hide_value = FALSE)) %>%
  ## 2nd-level row-wise splitting, and its column-wise analysis function, use n_unique_keys to remove duplicated records
  rtables::split_rows_by("level_2") %>%
  rtables::summarize_row_groups(cfun = count_items_cfun, extra_args = list(
    n_var = "aval_2", N_var = "aval_1", N_unique_keys = "SUBJID",
    n_unique_keys = c("SUBJID"), empty_row = FALSE
  )) %>%
  ## 3rd-level row-wise splitting, and its column-wise analysis function, use n_unique_keys to remove duplicated records
  rtables::split_rows_by("level_3") %>%
  rtables::summarize_row_groups(cfun = count_items_cfun, extra_args = list(
    n_var = "aval_3", n_unique_keys = c("SUBJID"), N_var = "aval_1", N_unique_keys = "SUBJID", N_index = 1,
    empty_row = TRUE
  ))

tbl_test3 <- tbl_recipe %>%
  rtables::build_table(df, col_counts = col_counts)
```


```{r}
#| echo: false
#| eval: true
#| message: FALSE
table_to_html(tbl_test3, to_html = FALSE)
```
